### ISSUE TITLE
Change last bin label in fprof

### ISSUE THREAD

**Issue by rgmiller** [olcf/pcircle#20]
The last bin in the histogram data generated by fprof is called “Bin>4.00_TiB”.  The ‘>’ in the name is causing some problems with Splunk.  If I just want to plot the value, the label is fine, but if I want to do any math (such as divide by the total number of files to get a percentage), the ‘>’ confuses Splunk.

Can we change the label to something like “Bin_GT_4.00_TiB”?

**Comment by fwang2** [comment]
New bin labels for consistency: 

['Bin_LE_4.00_KiB',
 'Bin_LE_8.00_KiB',
 'Bin_LE_16.00_KiB',
 'Bin_LE_32.00_KiB',
 'Bin_LE_64.00_KiB',
 'Bin_LE_128.00_KiB',
 'Bin_LE_256.00_KiB',
 'Bin_LE_512.00_KiB',
 'Bin_LE_1.00_MiB',
 'Bin_LE_2.00_MiB',
 'Bin_LE_4.00_MiB',
 'Bin_LE_16.00_MiB',
 'Bin_LE_32.00_MiB',
 'Bin_LE_64.00_MiB',
 'Bin_LE_128.00_MiB',
 'Bin_LE_256.00_MiB',
 'Bin_LE_512.00_MiB',
 'Bin_LE_1.00_GiB',
 'Bin_LE_4.00_GiB',
 'Bin_LE_64.00_GiB',
 'Bin_LE_128.00_GiB',
 'Bin_LE_256.00_GiB',
 'Bin_LE_512.00_GiB',
 'Bin_LE_1.00_TiB',
 'Bin_LE_4.00_TiB',
 'Bin_GT_4.00_TiB']

**Comment by fwang2** [comment]
done and tested.
