### ISSUE TITLE
Divide by zero error when total_file_size=0

### ISSUE THREAD

**Issue by cmharr** [olcf/pcircle#46]
In fprof.py, version 0.16+51, lines 619 and 640 divide by total_file_size. In cases where you profile a directory that may have all zero-byte files, this generates a divide-by-zero error: 
`RuntimeWarning: invalid value encountered in divide
`

**Comment by fwang2** [comment]
yep, that's a bug, I just committed the fix to the dev branch. Thanks a lot.

Feiyi
