### ISSUE TITLE
Number of sparse files likely incorrect

### ISSUE THREAD

**Issue by cmharr** [olcf/pcircle#48]
I don't have proof the number of sparse files in the epilog is incorrect, but it seems unlikely that ~80% of the files are sparse:
`Fprof epilogue:

        Directory count:         49,110,551
        Sym links count:         8,101,615
        Hard linked files:       30,179
        File count:              951,544,073
        Sparse files:            757,405,662
        Skipped count:           298,185
        Total file size:         2741.97 TiB
        Avg file size:           3.02 MiB
        Max files within dir:    1,536,921
        Tree walk time:          15h 34m
        Scanning rate:           18000/s
`
Is there an easy way to print out a subset (I can kill the job partway through) of what fprof thinks are sparse files so I can manually inspect them?

**Comment by fwang2** [comment]
right now, the detection logic is:
   sparse file if  actually allocated block (st_blocks) * 512 < file size (st_size)
of course hard-coded 512 is non-portable. Are you running on Lustre or GPFS?

I can print debug messages for detected spare files, but this will generate a ton of other protocol messages as well.

**Comment by cmharr** [comment]
This is Lustre (v. 2.5.5).

**Comment by fwang2** [comment]
I checked with a senior Lustre developer and see if there are better ways, but for now, st_blocks seem to be the simplest way to get estimates.  I have pushed a `--sparse` flags (dev branch) to print out detected sparse files, can you do a partial run and see why this is not right?

**Comment by cmharr** [comment]
I've checked several thousand of the files deemed sparse files and sure 
enough, they are sparse. I find that surprising, but go ahead and close 
the ticket. Thanks for tips.

Cameron

**Comment by fwang2** [comment]
I find that surprising as well: maybe most apps doing non-overlapping writing are not writing as much as they should (or app developers left some buffer space intentionally), I will take another look at olcf side and see this is something more universal. For now, I am closing this thread and we can revisit this as needed. Thanks!
