### ISSUE TITLE
Can a files-per-directory histogram option be implemented?

### ISSUE THREAD

**Issue by cmharr** [olcf/pcircle#51]
Folks here keep getting excited about fprof and coming up with new ideas for it. 
We're on a drive right now to better understand users' I/O behavior and one question we'd like to understand is why would someone put millions of files in a directory (one profile shows 26M). Would it be possible to include an option to spit out a histogram (similar to file size) with buckets of files/directory? 

For instance, we could use a logarithmic progression such as:
<=0 files per directory
<=10
<=100
<=1000
<=10000
...
<=100M

**Comment by fwang2** [comment]
It is a good suggestion and would be useful in general, let me see what I
can do.

thanks

Feiyi

**Comment by fwang2** [comment]
hi Cameron,
I did a quick prototype - haven't spent much time to check its correctness
yet, but it passed my small test. If you have time, please help to run some
sanity test.

to generate a directory entries profile:
```
fprof --dirprof --dirbins 0 10 100 1000 /path/to/directory
```

Basically, you supply your own bins: a list of sorted integers. I could
probably do a default list, but this seems more flexible.

Also note that, it is not counting the directories, it is counting
(profiling) all entries (file or dir) under each directory.

Let me know what you think. thanks

Feiyi

**Comment by cmharr** [comment]
I didn't get time to run it today, but will tomorrow. Note that as is, 
it doesn't seem to know when to look for the directory path. As for 
specifying bins, I think It'd be good to have default bins but also let 
the user specify their own if so desired.

[fprof@surface86 fprof]$ ./python-dev/bin/fprof --dirprof --dirbins 0 10 100 1000 /p/lscratchh/fprof
usage: fprof [-h] [--version] [-v] [--loglevel LOGLEVEL] [-i INTERVAL]
              [--perfile] [--inodesz INODESZ] [--gpfs-block-alloc] [--dii]
              [--top TOP] [--perprocess] [--syslog] [--profdev] [--item ITEM]
              [--exclude FILE] [--lustre-stripe] [--stripe-threshold N]
              [--stripe-output] [--sparse] [--cpr] [--cpr-per-file] [--dirprof]
              [--dirbins INT [INT ...]]
              path [path ...]
argument --dirbins: invalid int value: '/p/lscratchh/fprof'

**Comment by cmharr** [comment]
I actually tried that earlier with the same result but I can try again 
tomorrow.

**Comment by fwang2** [comment]
Cameron,  now bins take default value if you don't supply it, the run should be simpler:

`fprof --dirprof /path/to/somewhere`

let me know if this works for you.

**Comment by cmharr** [comment]
Thanks Feiyi. I was actually just typing a response to the last message after running the command. I must have typo'd yesterday because today the command worked if I put the path before the --dirbins flag.

However, the output doesn't reflect what I'd expect, so perhaps I just need to be educated. I would expect the sum of the number of entries in the directory histogram to roughly match the number of files scanned in the directory path, allowing us to understand how files are grouped. A list of the files in the directory path is attached and the fprof output is below.
[filelist.txt](https://github.com/olcf/pcircle/files/1679775/filelist.txt)
```
Running Parameters:

	fprof version:      0.17-b1+4.g5fb68b7  
	Full rev id:        5fb68b7cae1a5a85ce255f4b03244bfce189ff3c
	Num of hosts:       1                   
	Num of processes:   1                   
	Syslog report:      no                  
	Dir bins:           [0, 10, 100, 1000]  
	Stripe analysis:    no                  
	Root path:          ['/p/lscratchh/fprof']

Start profiling ...

Fprof epilogue:

	Directory count:         26                  
	Sym links count:         0                   
	Hard linked files:       0                   
	File count:              972                 
	Zero byte files:         1                   
	Sparse files:            971                 
	Skipped count:           0                   
	Total file size:         485.63 GiB          
	Avg file size:           511.61 MiB          
	Max files within dir:    192                 
	Tree walk time:          0.16s               
	Scanning rate:           6271/s              
	Fprof loads:             [998]               

Fileset Histogram

	   Buckets        Num of Files         Size       %(Files)        %(Size)

	<= 0.00 KiB       1                0.00 KiB          0.10%          0.00%
	<= 4.00 KiB       0                0.00 KiB          0.00%          0.00%
	<= 8.00 KiB       0                0.00 KiB          0.00%          0.00%
	<= 16.00 KiB      0                0.00 KiB          0.00%          0.00%
	<= 32.00 KiB      0                0.00 KiB          0.00%          0.00%
	<= 64.00 KiB      0                0.00 KiB          0.00%          0.00%
	<= 128.00 KiB     0                0.00 KiB          0.00%          0.00%
	<= 256.00 KiB     0                0.00 KiB          0.00%          0.00%
	<= 512.00 KiB     0                0.00 KiB          0.00%          0.00%
	<= 1.00 MiB       0                0.00 KiB          0.00%          0.00%
	<= 2.00 MiB       0                0.00 KiB          0.00%          0.00%
	<= 4.00 MiB       0                0.00 KiB          0.00%          0.00%
	<= 16.00 MiB      0                0.00 KiB          0.00%          0.00%
	<= 32.00 MiB      0                0.00 KiB          0.00%          0.00%
	<= 64.00 MiB      0                0.00 KiB          0.00%          0.00%
	<= 128.00 MiB     0                0.00 KiB          0.00%          0.00%
	<= 256.00 MiB     0                0.00 KiB          0.00%          0.00%
	<= 512.00 MiB     203            101.49 GiB         20.88%         20.90%
	<= 1.00 GiB       768            384.13 GiB         79.01%         79.10%
	<= 4.00 GiB       0                0.00 KiB          0.00%          0.00%
	<= 64.00 GiB      0                0.00 KiB          0.00%          0.00%
	<= 128.00 GiB     0                0.00 KiB          0.00%          0.00%
	<= 256.00 GiB     0                0.00 KiB          0.00%          0.00%
	<= 512.00 GiB     0                0.00 KiB          0.00%          0.00%
	<= 1.00 TiB       0                0.00 KiB          0.00%          0.00%
	<= 4.00 TiB       0                0.00 KiB          0.00%          0.00%
	>  4.00 TiB       0                0.00 KiB          0.00%          0.00%


Directory Histogram

	   Buckets        Num of Entries      %(Entries)

	<= 0              16                      61.54%
	<= 10             3                       11.54%
	<= 100            2                        7.69%
	<= 1000           5                       19.23%
```

**Comment by cmharr** [comment]
Assuming you are now tracking the directories, it would be nice to also have a way to print out the top N directories with the most files, similar to the top N largest files.

**Comment by fwang2** [comment]
Let me take an example and see this will make sense:

Assume you have a directory structure like the following:


```
dirsamples/
├── dir1
│   ├── dir4
│   ├── dir5
│   ├── file4
│   ├── file5
│   └── file6
├── dir2
│   ├── dir6
│   ├── dir7
│   └── dir8
├── dir3
├── file1
├── file2
└── file3
```

The directory profiling will output:

```
Directory Histogram

	   Buckets        Num of Entries      %(Entries)

	<= 0              6                       66.67%
	<= 4              1                       11.11%
	<= 8              2                       22.22%
	<= 10             0                        0.00%
```

For example: you have two directories `dirsamples` and `dir1` hold more than 4 but less than 8 entries. Thus the `<=8` shows 2.

Now let's count the number of directories that is empty: `dir4, dir5, dir6, dir7, dir8, dir3`, that is 6.

And `dir3` is the only one with 3 entries, thus `<=4` is 1.

That is how it was counted, let me know if it makes sense.

For top N, yes, let's track that with a new issue. 

Feiyi

**Comment by cmharr** [comment]
Feiyi, thank you. My accidental reading of the histogram as a table instead of a histogram was immediately obvious as soon as I saw your message. I'll do some additional verification on a larger data set and let you know.

**Comment by cmharr** [comment]
I scripted a verification check and your results look completely correct.
