### ISSUE TITLE
Run pcircle with openmpi library not in default directory

### ISSUE THREAD

**Issue by jxiong** [olcf/pcircle#61]
I have to run pcircle with openmpi instead of mpich since there are some weird dependency problem in our developing env.

After entering into python virtualenv, I can install pcircle as follows:

`CC=/usr/mpi/gcc/openmpi-3.0.0rc6/bin/mpicc pip2 install git+https://github.com/olcf/pcircle@dev`

However, it ran into errors when I was trying to execute `fprof`:

```
(pcircle)jinshan.xiong@dev-8e6d44e5:~/pcircle/bin$ ./fprof
Traceback (most recent call last):
  File "./fprof", line 9, in <module>
    load_entry_point('pcircle==0.17.1-1.gf2521cc', 'console_scripts', 'fprof')()
  File "/home/jinshan.xiong/pcircle/local/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jinshan.xiong/pcircle/local/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
    return ep.load()
  File "/home/jinshan.xiong/pcircle/local/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/jinshan.xiong/pcircle/local/lib/python2.7/site-packages/pcircle/fprof.py", line 19, in <module>
    from mpi4py import MPI
ImportError: /home/jinshan.xiong/pcircle/local/lib/python2.7/site-packages/mpi4py/MPI.so: undefined symbol: ompi_mpi_logical8
```

`MPI.so` above depends on `libopenmpi.so` for the missing symbol. The weird thing is that it doesn't even have openmpi library in its dependency list.

```
(pcircle)jinshan.xiong@dev-8e6d44e5:~/pcircle/bin$ ldd /home/jinshan.xiong/pcircle/local/lib/python2.7/site-packages/mpi4py/MPI.so
	linux-vdso.so.1 =>  (0x00007ffed93c1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd93b360000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd93af9b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd93b903000)
```
I tried to specific `LD_LIBRARY_PATH` but it didn't help. Does anyone else have experience to make it work? My testing env is ubuntu 14.04 LTS.

**Comment by jxiong** [comment]
`LD_PRELOAD` worked but I don't think this is the best way of doing it.

**Comment by fwang2** [comment]
pcircle doesn't directly depend on mpich or openmpi. Instead, it relys on
mpi4py package, which usually have two both bindings - one for mpich, one
for openmpi (available through RHEL / EPL). If you have to use the latest
mpi release, then you might have to install mpi4py from source (python
setup.py install)

**Comment by fwang2** [comment]
btw - when you provided CC=/path/to/mpicc, you are essentially telling
mpi4py where to locate mpicc to compile into .so, but when you start
picirlce/fprof, fprof will try to import mpi4py, and mpi4py at that point
don't know where is your mpi environment if you haven't persisted the
environment. Maybe the reasonable path is to make sure you MPI
environment is properly set through Module/Lmod or other mechanisms.

**Comment by jxiong** [comment]
Somehow github didn't notify me.

We have resolved the dependency issue, and thank you for your hints.

**Comment by gyh75520** [comment]
@jxiong I am having trouble on using the command LD_PRELOAD. I have no idea about how to specify the path to make it work.
